//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliances_Used
    {
        public string Id { get; set; }
        public string Appliance_Name { get; set; }
        public string Recipe_Id { get; set; }
        public string Appliance_Name_Search { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
