//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public string Recipe_Ingredient_ID { get; set; }
        public string Recipe_ID { get; set; }
        public string Ingredient_Name { get; set; }
        public string Measurement { get; set; }
        public string Ingredient_Name_Search { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
