//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rdbEntities : DbContext
    {
        public rdbEntities()
            : base("name=rdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appliances_Used> Appliances_Used { get; set; }
        public virtual DbSet<AppliancesList> AppliancesLists { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Dietary_Tags> Dietary_Tags { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientsList> IngredientsLists { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<Liked_Recipes> Liked_Recipes { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Security_Questions> Security_Questions { get; set; }
        public virtual DbSet<tagsList> tagsLists { get; set; }
        public virtual DbSet<ThemeGallery> ThemeGalleries { get; set; }
        public virtual DbSet<User_Defined_Tags> User_Defined_Tags { get; set; }
        public virtual DbSet<UserOption> UserOptions { get; set; }
        public virtual DbSet<News> News { get; set; }
    }
}
