//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Appliances_Used = new HashSet<Appliances_Used>();
            this.Comments = new HashSet<Comment>();
            this.Dietary_Tags = new HashSet<Dietary_Tags>();
            this.Ingredients = new HashSet<Ingredient>();
            this.Liked_Recipes = new HashSet<Liked_Recipes>();
            this.Pictures = new HashSet<Picture>();
            this.User_Defined_Tags = new HashSet<User_Defined_Tags>();
        }
    
        public string Recipe_ID { get; set; }
        public string Recipe_Name { get; set; }
        public string Recipe_Short_Description { get; set; }
        public string Recipe_Description { get; set; }
        public string Cooking_Time { get; set; }
        public int Recipe_Visibility { get; set; }
        public string Date_Uploaded { get; set; }
        public int Number_Of_Views { get; set; }
        public string Instructions { get; set; }
        public string Display_Picture_Location { get; set; }
        public string User_ID { get; set; }
        public string Recipe_Search_Name { get; set; }
        public string Cooking_Time_Search_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appliances_Used> Appliances_Used { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dietary_Tags> Dietary_Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liked_Recipes> Liked_Recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Defined_Tags> User_Defined_Tags { get; set; }
    }
}
