//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string Report_Id { get; set; }
        public string Type { get; set; }
        public string Comment_Or_Recipe_Id { get; set; }
        public string Reason_For_Report { get; set; }
        public string Content_Creator_Name { get; set; }
        public string Reporter_Name { get; set; }
        public string Content_Creator_Id { get; set; }
        public string Reporter_Id { get; set; }
        public string Comment { get; set; }
        public string Recipe_Name { get; set; }
        public string Recipe_ID { get; set; }
        public string Comment_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
