//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Questions
    {
        public string Security_Question_ID { get; set; }
        public string Security_Question { get; set; }
        public string Security_Answer { get; set; }
        public string User_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
