//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tagsList
    {
        public int tag_id { get; set; }
        public string tag_Name { get; set; }
        public Nullable<int> Occurances { get; set; }
        public Nullable<System.DateTime> start_Date { get; set; }
        public int permanant { get; set; }
        public string AlphaTag { get; set; }
    }
}
