//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeGallery
    {
        public string Theme_Id { get; set; }
        public string Name { get; set; }
        public int User_Custom_Theme { get; set; }
        public string Text_Color { get; set; }
        public string Background_Color { get; set; }
        public string Contrast_Box_Background_Color { get; set; }
        public string Background_Image { get; set; }
        public string Background_Box_Color { get; set; }
        public string Background_Box_Opacity { get; set; }
        public string Background_Color_Opacity { get; set; }
        public string Contrast_Box_Background_Color_Opacity { get; set; }
        public string Background_Image_Color_Or_Theme { get; set; }
        public string Input_Color { get; set; }
        public string Input_Opacity { get; set; }
        public string User_Id { get; set; }
        public int Permenant { get; set; }
        public string Hr_Color { get; set; }
        public string Logo_Facebook { get; set; }
        public string Logo_Twitter { get; set; }
        public string Logo_Reddit { get; set; }
        public string Logo_BitBucket { get; set; }
        public string Logo_Main { get; set; }
        public string Logo_Info { get; set; }
        public string Theme_Icon_Path { get; set; }
        public string Logo_Save { get; set; }
        public string Logo_Garbage { get; set; }
        public string Arrow_Left { get; set; }
        public string Arrow_Right { get; set; }
        public string Arrow_Up { get; set; }
        public string Arrow_Down { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
