//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOption
    {
        public string User_Id { get; set; }
        public int Search_Visibility { get; set; }
        public int Recipes_Per_Page { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
